# $ Standardized Variable = \frac{x - \mu}{\sigma} $

x = Original variable
$ \mu $ = Mean of original varible
$ \sigma $ = Std dev of original variable

Hint:
$ \sigma = \sum \frac{(x - \mu)^2}{n-1} $ For samples

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from sklearn.linear_model import LinearRegression

In [3]:
data = pd.read_csv('/Users/josephdecommer/Documents/coding2022/Python/Data Sets/1.02. Multiple linear regression.csv')
data.head()

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

# declare variables

In [4]:
x = data[['SAT', 'Rand 1,2,3']]
y = data['GPA']


# Standardization

In [5]:
from sklearn.preprocessing import StandardScaler

In [6]:
scaler = StandardScaler()

In [8]:
scaler.fit(x) # fit calculates and stores the mean and stdev of each feature

StandardScaler()

In [10]:
x_scaled = scaler.transform(x) # This can be used whenever new data in introduced

In [12]:
x_scaled # all data is standardized

array([[-1.26338288, -1.24637147],
       [-1.74458431,  1.10632974],
       [-0.82067757,  1.10632974],
       [-1.54247971,  1.10632974],
       [-1.46548748, -0.07002087],
       [-1.68684014, -1.24637147],
       [-0.78218146, -0.07002087],
       [-0.78218146, -1.24637147],
       [-0.51270866, -0.07002087],
       [ 0.04548499,  1.10632974],
       [-1.06127829,  1.10632974],
       [-0.67631715, -0.07002087],
       [-1.06127829, -1.24637147],
       [-1.28263094,  1.10632974],
       [-0.6955652 , -0.07002087],
       [ 0.25721362, -0.07002087],
       [-0.86879772,  1.10632974],
       [-1.64834403, -0.07002087],
       [-0.03150724,  1.10632974],
       [-0.57045283,  1.10632974],
       [-0.81105355,  1.10632974],
       [-1.18639066,  1.10632974],
       [-1.75420834,  1.10632974],
       [-1.52323165, -1.24637147],
       [ 1.23886453, -1.24637147],
       [-0.18549169, -1.24637147],
       [-0.5608288 , -1.24637147],
       [-0.23361183,  1.10632974],
       [ 1.68156984,

## Regression with scaled features

In [13]:
reg = LinearRegression()
reg.fit(x_scaled,y)

LinearRegression()

In [14]:
reg.coef_

array([ 0.17181389, -0.00703007])

In [15]:
reg.intercept_

3.330238095238095

Summary Table

In [18]:
reg_summary = pd.DataFrame([['Bias'], ['SAT'], ['Rand 1,2,3']], columns=['Features'])
reg_summary['Weights'] = reg.intercept_, reg.coef_[0], reg.coef_[1]

In [19]:
reg_summary # Weights is for coefficients after standarization, intercept is called bias, lower weights become more worthless

Features   Weights
0        Bias  3.330238
1         SAT  0.171814
2  Rand 1,2,3 -0.007030

## Making predictions with standardized coefficients (weights)

In [27]:
new_data = pd.DataFrame(data=[[1700,2],[1800, 1]])
new_data

0  1
0  1700  2
1  1800  1

In [28]:
reg.predict(new_data) # spits out the bullshitz!

array([295.39979563, 312.58821497])

In [29]:
new_data_scaled = scaler.transform(new_data)
new_data_scaled

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[-1.39811928, -0.07002087],
       [-0.43571643, -1.24637147]])

In [30]:
reg.predict(new_data_scaled)

array([3.09051403, 3.26413803])

## Removing the random rand 1,2,3 variable

In [34]:
reg_simple = LinearRegression()
x_simple_matrix = x_scaled[:,0].reshape(-1,1)
reg_simple.fit(x_simple_matrix, y)

LinearRegression()

In [35]:
reg_simple.predict(new_data_scaled[:,0].reshape(-1,1))

array([3.08970998, 3.25527879])