In [1]:
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
a = np.arange(1, 101)

In [3]:
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [15]:
b = np.arange(501,601)

In [16]:
b

array([501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513,
       514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526,
       527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539,
       540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552,
       553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565,
       566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578,
       579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591,
       592, 593, 594, 595, 596, 597, 598, 599, 600])

In [17]:
train_test_split(a)

[array([ 33,  81,  13,  40,  55,  30,  26,  57,  69,  68,  29,  23,   1,
          5,  32,   9,  96,  44,   3,   7,  31,  14,  87,  72,  27,  83,
         59,  17,  43,  51,   4,  42,  84,  73,  86,  65,  25,  15,  89,
         36,  22,  63,  49,  16,  78,  56,  94,  88,  70,  54,  11,  39,
         24,  95, 100,  53,  19,  74,  18,  90,  10,  58,  92,  37,  21,
         35,  99,  98,  77,  28,  47,  79,  45,   8,  12]),
 array([61, 64,  2, 80, 76, 71, 93, 82, 48, 67, 52, 41, 75, 66, 85, 34, 60,
        46, 97, 62, 50,  6, 20, 38, 91])]

In [29]:
a_train, a_test, b_train, b_test = train_test_split(a, b, test_size=0.2, random_state=43)

In [30]:
a_train.shape, a_test.shape

((80,), (20,))

In [31]:
a_train

array([ 45,  13,  79,  95,  38,  93,  98,  57,  64,  47,   9,  34,  46,
        20,  15,  94,  74,  40,  25,   7,  63,  24,  19,  43,  81,  87,
        32,  68,  28,  11,  41,  71,  97,  89,  27,  55,  72,  30,  26,
        44,  42,  73,   4,  82,  54,  78,  62,   8,  29, 100,  53,  49,
        83,  61,  75,  33,  48,  77,  37,   5,  91,  85,  35,  66,  76,
        51,  36,  99,  88,  31,  67,  60,  18,  52,  17,  59,  22,  50,
        65,  69])

In [32]:
a_test

array([21,  3, 16, 23, 58, 92, 70, 56, 12, 80, 10, 39, 86,  1, 90, 14,  6,
        2, 96, 84])

In [33]:
b_train.shape, b_test.shape

((80,), (20,))

In [34]:
b_train

array([545, 513, 579, 595, 538, 593, 598, 557, 564, 547, 509, 534, 546,
       520, 515, 594, 574, 540, 525, 507, 563, 524, 519, 543, 581, 587,
       532, 568, 528, 511, 541, 571, 597, 589, 527, 555, 572, 530, 526,
       544, 542, 573, 504, 582, 554, 578, 562, 508, 529, 600, 553, 549,
       583, 561, 575, 533, 548, 577, 537, 505, 591, 585, 535, 566, 576,
       551, 536, 599, 588, 531, 567, 560, 518, 552, 517, 559, 522, 550,
       565, 569])

In [35]:
b_test

array([521, 503, 516, 523, 558, 592, 570, 556, 512, 580, 510, 539, 586,
       501, 590, 514, 506, 502, 596, 584])